[tool.poetry]
name = "repl_python3_Unit3-02"
version = "0.1.0"
description = ""
authors = ["UhhPat <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
constants = "^0.6.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
